config/routes.rb
Rails.application.routes.draw do
  get 'mains/index'
  devise_for :users, controllers: {registrations: 'users/registrations' }
  
  root to: "mains#index"
  resources :items do
    resources :orders, only: [:index, :create]
  end
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
  resources :prototypes, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :index]
  end
  resources :users
  resources :calls, only: [:index]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'LINE' },
    { id: 3, name: 'Facebook' },
    { id: 4, name: 'instagram' },
    { id: 5, name: 'その他' },

  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prototype

  validates :text,      presence: true
end

app/models/delivery_day.rb
class DeliveryDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '2~3日で発送' },
    { id: 3, name: '7~10日で発送' },
    { id: 4, name: '10日以上で発送' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :order
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :product_status
  belongs_to :shipping_fee_burden
  belongs_to :prefecture
  belongs_to :delivery_day

  with_options presence: true do
    validates :image
    validates :title
    validates :text
    validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }, format: { with: /\A[0-9]+\z/ }
    with_options numericality: { other_than: 1, message: 'を選択してください' } do
      validates :category_id
      validates :product_status_id
      validates :shipping_fee_burden_id
      validates :prefecture_id
      validates :delivery_day_id
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :postal_code, :prefecture_id, :municipality, :address, :building_name, :phone_number, :user_id, :item_id, :token

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/ }
    validates :prefecture_id, numericality: { other_than: 1, other_than: 49 }
    validates :municipality, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :address
    validates :phone_number, numericality: {}, length: { minimum: 10, maximum: 11 }
    validates :user_id
    validates :item_id
    validates :token
  end

  def save
    order = Order.create(user_id: user_id, item_id: item_id)
    Address.create(postal_code: postal_code, prefecture_id: prefecture_id, municipality: municipality, address: address, building_name: building_name, phone_number: phone_number, order_id: order.id)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }, { id: 49, name: '全国' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/product_status.rb
class ProductStatus < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '新品' },
    { id: 3, name: '中古' },
    
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
                    
  validates :title,      presence: true
  validates :text, presence: true
  validates :image,      presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  has_many :orders

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :prototypes 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
  mount_uploader :image, ImageUploader

  with_options on: :create do
    with_options presence: true do
      validates :nickname 
      validates :birthday 
      validates :image 

      with_options format: { with: /\A[ぁ-んァ-ン一-龥々]/ } do
        validates :first_name
        validates :last_name
      end

      with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
        validates :first_name_kana
        validates :last_name_kana
      end
    end
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mains/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      <%= image_tag "clw.png", class:"list-pict-ori" %>
    </h2>
    <p class='service-explain'>
      -SNSをもっと身近に-
    </p>
    <%# <div class='store-btn'> %>
      <%#= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%#= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
      
    <%# </div> %>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>
  <div class='select-reason-contents-ori'>
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= link_to image_tag("ope1.png", class:"list-pict"), calls_path %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'></span>
          オペレーターに電話する
        </h3>
      </li>
      <li class='list'>
        <%= link_to image_tag("tokou.png", class:"list-pict"), prototypes_path %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'></span>
          写真を投稿する
        </h3>
      </li>
      <li class='list'>
        <%= link_to image_tag("chat1.png", class:"list-pict"), rooms_path %>
        <h3 class='reason-list-text'>
          チャットをする
          <span class='reason-list-blue-text'></span>
        </h3>
      </li>
      <li class='list'>
        <%= link_to image_tag("hon.png", class:"list-pict"), items_path %>
        <h3 class='reason-list-text'>
          教科書を購入する
          <span class='reason-list-blue-text'></span>
        </h3>
        
      </li>
      <li class='list'>
        <%= link_to image_tag("hito.png", class:"list-pict"), current_user %>
        <h3 class='reason-list-text'>
          プロフィールを確認する
          <span class='reason-list-blue-text'></span>
        </h3>
      </li>
      <li class='list'>
        <%= link_to image_tag("hitohen.png", class:"list-pict"), edit_user_registration_path %>
        <h3 class='reason-list-text'>
          プロフィールを編集する
          <span class='reason-list-blue-text'></span>
        </h3>
      </li>
    </ul>
  </div>
  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents-ori'>
    <h2 class='title-ori1'>
      アクティブシニアとSNSを繋げたい
    </h2>
    <h2 class='title-ori2'>
      connectは「始めやすい、わかりやすい」を理念としたSNS学習サービスアプリです
    </h2>
    <h2 class='title-ori2'>
      弊社サービスを通して、SNSの基本を学ぶことで
    </h2>
    <h2 class='title-ori2'>
      より一層充実したセカンドライフを過ごして頂けることを願っております
  </div>
  
  <div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    SNSをもっと身近に
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
  
</div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
 
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='select-reason-contents-ori2'>
    <h2 class='title-ori1'>
      主な3つの特徴
    </h2>
    <h2 class='title-ori6'>
      <%= image_tag "toku1.png", class:"ad-footer-contents-ori2" %>
    </h2>
    <h2 class='title-ori6'>
      <%= image_tag "toku2.png", class:"ad-footer-contents-ori2" %>
    </h2>
    <h2 class='title-ori6'>
      <%= image_tag "toku3.png", class:"ad-footer-contents-ori2" %>
    </h2>
  </div>

  <%# /FURIMAの特徴 %>


</div>
<%#= link_to('items/new', class: 'purchase-btn') do %>
  <%# <span class='purchase-btn-text'>出品する</span> %>
  <%#= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<%# <% end %>
<%#= render "shared/footer" %>
<div class='footer1'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>connectについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'connect利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>各種機能について</h2>
      <ul>
        <li><%= link_to '商品を購入する', items_path, class: "footer-link" %></li>
        <li><%= link_to 'チャットを利用する', rooms_path, class: "footer-link" %></li>
        <li><%= link_to '投稿を利用する', prototypes_path, class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>登録情報について</h2>
      <ul>
        <li><%= link_to 'プロフィールを確認する', current_user, class: "footer-link" %></li>
        <li><%= link_to 'プロフィールを編集する', edit_user_registration_path, class: "footer-link" %></li>
      </ul>
    </div>
    
  </div>
  <%= link_to image_tag("clw.png", class:"logo-white"), "#" %>
  <p>© connect</p>
</div>